In [1]:
import numpy as np
import pandas as pd
from scipy import stats

In [2]:
active_validators_size = pd.read_csv('../int/active_validators_size.csv')
active_validators_category = pd.read_csv('../int/active_validators_category.csv')
active_validators_pool = pd.read_csv('../int/active_validators_pool.csv')

In [4]:
active_validators_size_set = active_validators_size
active_validators_size_set['slot'] = active_validators_size_set['slot'] // 300 * 300

# Create a dictionary for aggregation
agg_dict = {col: 'last' for col in active_validators_size_set.columns}

# Group by 'slot' and apply the aggregation
active_validators_size_set = active_validators_size_set.groupby('slot').agg(agg_dict).reset_index(drop=True)

active_validators_size_set

            slot       1      100+     2-5    20-99     6-19      total
0            0.0  1020.0   13599.0  1049.0   3568.0   1827.0    21063.0
1          300.0  1020.0   13599.0  1049.0   3568.0   1827.0    21063.0
2          600.0  1020.0   13599.0  1049.0   3568.0   1827.0    21063.0
3          900.0  1020.0   13599.0  1049.0   3568.0   1827.0    21063.0
4         1200.0  1023.0   13599.0  1050.0   3568.0   1831.0    21071.0
...          ...     ...       ...     ...      ...      ...        ...
29949  8984700.0  9843.0  919814.0  9925.0  44358.0  18082.0  1002022.0
29950  8985000.0  9845.0  919872.0  9925.0  44358.0  18082.0  1002082.0
29951  8985300.0  9845.0  919938.0  9925.0  44358.0  18082.0  1002148.0
29952  8985600.0  9845.0  920015.0  9926.0  44358.0  18083.0  1002227.0
29953  8985900.0  9845.0  920070.0  9926.0  44358.0  18083.0  1002282.0

[29954 rows x 7 columns]

In [5]:
# Calculate percent change
active_validators_size_change = active_validators_size_set.pct_change() * 100

# Replace the original DataFrame with the percent change values
active_validators_size_change

# If you want to keep the slot column intact and only apply the percent change to other columns
active_validators_size_change['slot'] = active_validators_size_set['slot']

active_validators_size_change = active_validators_size_change.drop(index=0)

# Display the DataFrame with percent changes
active_validators_size_change

            slot         1      100+       2-5  20-99      6-19     total
1          300.0  0.000000  0.000000  0.000000    0.0  0.000000  0.000000
2          600.0  0.000000  0.000000  0.000000    0.0  0.000000  0.000000
3          900.0  0.000000  0.000000  0.000000    0.0  0.000000  0.000000
4         1200.0  0.294118  0.000000  0.095329    0.0  0.218938  0.037981
5         1500.0  0.000000  0.286786  0.000000    0.0  0.054615  0.189834
...          ...       ...       ...       ...    ...       ...       ...
29949  8984700.0 -0.030469 -0.000326  0.000000    0.0  0.000000 -0.000599
29950  8985000.0  0.020319  0.006306  0.000000    0.0  0.000000  0.005988
29951  8985300.0  0.000000  0.007175  0.000000    0.0  0.000000  0.006586
29952  8985600.0  0.000000  0.008370  0.010076    0.0  0.005530  0.007883
29953  8985900.0  0.000000  0.005978  0.000000    0.0  0.000000  0.005488

[29953 rows x 7 columns]

In [6]:
active_validators_category_set = active_validators_category
active_validators_category_set['slot'] = active_validators_category_set['slot'] // 300 * 300

# Create a dictionary for aggregation
agg_dict = {col: 'last' for col in active_validators_category_set.columns}

# Group by 'slot' and apply the aggregation
active_validators_category_set = active_validators_category_set.groupby('slot').agg(agg_dict).reset_index(drop=True)

active_validators_category_set

,slot,CEX,Liquid Restaking,Liquid Staking,Solo Stakers,Staking Pools,Unidentified,Unnamed: 7,total
0,0.0,2927.0,0.0,559.0,218.0,13.0,14105.0,0.0,17822.0
1,300.0,2927.0,0.0,559.0,218.0,13.0,14105.0,0.0,17822.0
2,600.0,2927.0,0.0,559.0,218.0,13.0,14105.0,0.0,17822.0
3,900.0,2927.0,0.0,559.0,218.0,13.0,14105.0,0.0,17822.0
4,1200.0,2927.0,0.0,559.0,218.0,13.0,14112.0,0.0,17829.0
...,...,...,...,...,...,...,...,...,...
29949,8984700.0,238164.0,44028.0,331431.0,630.0,18934.0,263353.0,0.0,896540.0
29950,8985000.0,238164.0,44078.0,331429.0,630.0,18934.0,263373.0,0.0,896608.0
29951,8985300.0,238164.0,44078.0,331425.0,630.0,18934.0,263443.0,0.0,896674.0
29952,8985600.0,238165.0,44087.0,331425.0,630.0,18939.0,263501.0,0.0,896747.0
29953,8985900.0,238161.0,44151.0,331421.0,630.0,18939.0,263500.0,0.0,896802.0

In [7]:
# Calculate percent change
active_validators_category_change = active_validators_category_set.pct_change() * 100

# Replace the original DataFrame with the percent change values
active_validators_category_change

# If you want to keep the slot column intact and only apply the percent change to other columns
active_validators_category_change['slot'] = active_validators_category_set['slot']

active_validators_category_change = active_validators_category_change.drop(index=0)

# Display the DataFrame with percent changes
active_validators_category_change

,slot,CEX,Liquid Restaking,Liquid Staking,Solo Stakers,Staking Pools,Unidentified,Unnamed: 7,total
1,300.0,0.000000,NaN,0.000000,0.0,0.000000,0.000000,NaN,0.000000
2,600.0,0.000000,NaN,0.000000,0.0,0.000000,0.000000,NaN,0.000000
3,900.0,0.000000,NaN,0.000000,0.0,0.000000,0.000000,NaN,0.000000
4,1200.0,0.000000,NaN,0.000000,0.0,0.000000,0.049628,NaN,0.039277
5,1500.0,0.000000,NaN,0.000000,0.0,0.000000,0.283447,NaN,0.224354
...,...,...,...,...,...,...,...,...,...
29949,8984700.0,-0.004618,0.182033,-0.001207,0.0,0.000000,-0.025814,NaN,-0.000335
29950,8985000.0,0.000000,0.113564,-0.000603,0.0,0.000000,0.007594,NaN,0.007585
29951,8985300.0,0.000000,0.000000,-0.001207,0.0,0.000000,0.026578,NaN,0.007361
29952,8985600.0,0.000420,0.020418,0.000000,0.0,0.026408,0.022016,NaN,0.008141
29953,8985900.0,-0.001680,0.145168,-0.001207,0.0,0.000000,-0.000380,NaN,0.006133

In [8]:
active_validators_pool_set = active_validators_pool
active_validators_pool_set['slot'] = active_validators_pool_set['slot'] // 300 * 300

# Create a dictionary for aggregation
agg_dict = {col: 'last' for col in active_validators_pool_set.columns}

# Group by 'slot' and apply the aggregation
active_validators_pool_set = active_validators_pool_set.groupby('slot').agg(agg_dict).reset_index(drop=True)

active_validators_pool_set

,slot,Binance,Bitcoin Suisse,Coinbase,Ether.Fi,Kraken,Ledger Live,Lido,Mantle,OKX,Other Stakers,Rocketpool,total
0,0.0,1.0,2876.0,0.0,0.0,0.0,13.0,0.0,0.0,0.0,18153.0,20.0,21063.0
1,300.0,1.0,2876.0,0.0,0.0,0.0,13.0,0.0,0.0,0.0,18153.0,20.0,21063.0
2,600.0,1.0,2876.0,0.0,0.0,0.0,13.0,0.0,0.0,0.0,18153.0,20.0,21063.0
3,900.0,1.0,2876.0,0.0,0.0,0.0,13.0,0.0,0.0,0.0,18153.0,20.0,21063.0
4,1200.0,1.0,2876.0,0.0,0.0,0.0,13.0,0.0,0.0,0.0,18161.0,20.0,21071.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
29949,8984700.0,35167.0,19013.0,138340.0,33745.0,23748.0,14723.0,290691.0,14974.0,10877.0,396014.0,24730.0,1002022.0
29950,8985000.0,35167.0,19013.0,138340.0,33795.0,23748.0,14723.0,290691.0,14974.0,10877.0,396026.0,24728.0,1002082.0
29951,8985300.0,35167.0,19013.0,138340.0,33795.0,23748.0,14723.0,290691.0,14974.0,10877.0,396096.0,24724.0,1002148.0
29952,8985600.0,35167.0,19013.0,138340.0,33804.0,23748.0,14728.0,290691.0,14974.0,10877.0,396161.0,24724.0,1002227.0
29953,8985900.0,35167.0,19013.0,138336.0,33868.0,23748.0,14728.0,290691.0,14974.0,10877.0,396160.0,24720.0,1002282.0

In [9]:
# Calculate percent change
active_validators_pool_change = active_validators_pool_set.pct_change() * 100

# Replace the original DataFrame with the percent change values
active_validators_pool_change

# If you want to keep the slot column intact and only apply the percent change to other columns
active_validators_pool_change['slot'] = active_validators_pool_set['slot']

active_validators_pool_change = active_validators_pool_change.drop(index=0)

# Display the DataFrame with percent changes
active_validators_pool_change

,slot,Binance,Bitcoin Suisse,Coinbase,Ether.Fi,Kraken,Ledger Live,Lido,Mantle,OKX,Other Stakers,Rocketpool,total
1,300.0,0.0,0.0,NaN,NaN,NaN,0.00000,NaN,NaN,NaN,0.000000,0.000000,0.000000
2,600.0,0.0,0.0,NaN,NaN,NaN,0.00000,NaN,NaN,NaN,0.000000,0.000000,0.000000
3,900.0,0.0,0.0,NaN,NaN,NaN,0.00000,NaN,NaN,NaN,0.000000,0.000000,0.000000
4,1200.0,0.0,0.0,NaN,NaN,NaN,0.00000,NaN,NaN,NaN,0.044070,0.000000,0.037981
5,1500.0,0.0,0.0,NaN,NaN,NaN,0.00000,NaN,NaN,NaN,0.220252,0.000000,0.189834
...,...,...,...,...,...,...,...,...,...,...,...,...,...
29949,8984700.0,0.0,0.0,-0.006505,0.237636,0.0,0.00000,0.0,-0.013355,0.0,-0.018430,-0.008087,-0.000599
29950,8985000.0,0.0,0.0,0.000000,0.148170,0.0,0.00000,0.0,0.000000,0.0,0.003030,-0.008087,0.005988
29951,8985300.0,0.0,0.0,0.000000,0.000000,0.0,0.00000,0.0,0.000000,0.0,0.017676,-0.016176,0.006586
29952,8985600.0,0.0,0.0,0.000000,0.026631,0.0,0.03396,0.0,0.000000,0.0,0.016410,0.000000,0.007883
29953,8985900.0,0.0,0.0,-0.002891,0.189327,0.0,0.00000,0.0,0.000000,0.0,-0.000252,-0.016179,0.005488

In [10]:
active_validators_size_change.to_csv('../int/active_validators_size_change.csv')
active_validators_category_change.to_csv('../int/active_validators_category_change.csv')
active_validators_pool_change.to_csv('../int/active_validators_pool_change.csv')