In [1]:
import pandas as pd
import numpy as np
import pandasql as ps

In [2]:
validator_exits_size = pd.read_csv('../int/validator_exits_size.csv')
validator_exits_category = pd.read_csv('../int/validator_exits_category.csv')
validator_exits_pool = pd.read_csv('../int/validator_exits_pool.csv')
active_validators_size = pd.read_csv('../int/active_validators_size.csv')
active_validators_category = pd.read_csv('../int/active_validators_category.csv')
active_validators_pool = pd.read_csv('../int/active_validators_pool.csv')

In [3]:
validator_exits_size_set = validator_exits_size
validator_exits_size_set['slot'] = ((validator_exits_size_set['slot'] - 1200) // 300) * 300 + 1200

# Create a dictionary for aggregation
agg_dict = {col: 'sum' for col in validator_exits_size_set.columns if col != 'slot'}
agg_dict['slot'] = 'last'

# Group by 'slot' and apply the aggregation
validator_exits_size_set = validator_exits_size_set.groupby('slot').agg(agg_dict).reset_index(drop=True)

validator_exits_size_set

         1  100+  2-5  20-99  6-19  total       slot
0      0.0   0.0  0.0    0.0   0.0    0.0        0.0
1      0.0   0.0  0.0    0.0   0.0    0.0      300.0
2      0.0   0.0  0.0    0.0   0.0    0.0      600.0
3      0.0   0.0  0.0    0.0   0.0    0.0      900.0
4      0.0   0.0  0.0    0.0   0.0    0.0     1200.0
...    ...   ...  ...    ...   ...    ...        ...
29949  3.0  83.0  0.0    0.0   0.0   86.0  8984700.0
29950  0.0  12.0  0.0    0.0   0.0   12.0  8985000.0
29951  0.0   6.0  0.0    0.0   0.0    6.0  8985300.0
29952  1.0   0.0  0.0    0.0   0.0    1.0  8985600.0
29953  0.0   9.0  0.0    0.0   0.0    9.0  8985900.0

[29954 rows x 7 columns]

In [4]:
validator_exits_category_set = validator_exits_category
validator_exits_category_set['slot'] = ((validator_exits_category_set['slot'] - 1200) // 300) * 300 + 1200

# Create a dictionary for aggregation
agg_dict = {col: 'sum' for col in validator_exits_category_set.columns if col != 'slot'}
agg_dict['slot'] = 'last'

# Group by 'slot' and apply the aggregation
validator_exits_category_set = validator_exits_category_set.groupby('slot').agg(agg_dict).reset_index(drop=True)

validator_exits_category_set

,CEX,Liquid Restaking,Liquid Staking,Solo Stakers,Staking Pools,Unidentified,Unnamed: 7,total,slot
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,300.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,600.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,900.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1200.0
...,...,...,...,...,...,...,...,...,...
29949,11.0,0.0,4.0,0.0,0.0,68.0,0.0,83.0,8984700.0
29950,0.0,0.0,3.0,0.0,0.0,0.0,0.0,3.0,8985000.0
29951,0.0,0.0,4.0,0.0,0.0,2.0,0.0,6.0,8985300.0
29952,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,8985600.0
29953,4.0,0.0,4.0,0.0,0.0,1.0,0.0,9.0,8985900.0

In [5]:
validator_exits_pool_set = validator_exits_pool
validator_exits_pool_set['slot'] = ((validator_exits_pool_set['slot'] - 1200) // 300) * 300 + 1200

# Create a dictionary for aggregation
agg_dict = {col: 'sum' for col in validator_exits_pool_set.columns if col != 'slot'}
agg_dict['slot'] = 'last'

# Group by 'slot' and apply the aggregation
validator_exits_pool_set = validator_exits_pool_set.groupby('slot').agg(agg_dict).reset_index(drop=True)

validator_exits_pool_set

,Binance,Bitcoin Suisse,Coinbase,Ether.Fi,Kraken,Ledger Live,Lido,Mantle,OKX,Other Stakers,Rocketpool,total,slot
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,300.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,600.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,900.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1200.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
29949,0.0,0.0,9.0,0.0,0.0,0.0,0.0,2.0,0.0,73.0,2.0,86.0,8984700.0
29950,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,3.0,12.0,8985000.0
29951,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,4.0,6.0,8985300.0
29952,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,8985600.0
29953,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,4.0,9.0,8985900.0

In [6]:
active_validators_size = active_validators_size[active_validators_size['slot'].isin(validator_exits_size_set['slot'])]
active_validators_size.reset_index(inplace=True)
active_validators_size = active_validators_size.drop(columns=['index'])

active_validators_category = active_validators_category[active_validators_category['slot'].isin(validator_exits_category_set['slot'])]
active_validators_category.reset_index(inplace=True)
active_validators_category = active_validators_category.drop(columns=['index'])

active_validators_pool = active_validators_pool[active_validators_pool['slot'].isin(validator_exits_pool_set['slot'])]
active_validators_pool.reset_index(inplace=True)
active_validators_pool = active_validators_pool.drop(columns=['index'])

In [7]:
slots = validator_exits_size_set['slot']
columns = validator_exits_size_set.columns.drop('slot')
validator_exits_size_percentage = validator_exits_size_set[columns].divide(active_validators_size[columns]) * 100
validator_exits_size_percentage['slot'] = slots

validator_exits_size_percentage

              1      100+  2-5  20-99  6-19     total       slot
0      0.000000  0.000000  0.0    0.0   0.0  0.000000        0.0
1      0.000000  0.000000  0.0    0.0   0.0  0.000000      300.0
2      0.000000  0.000000  0.0    0.0   0.0  0.000000      600.0
3      0.000000  0.000000  0.0    0.0   0.0  0.000000      900.0
4      0.000000  0.000000  0.0    0.0   0.0  0.000000     1200.0
...         ...       ...  ...    ...   ...       ...        ...
29949  0.030469  0.009024  0.0    0.0   0.0  0.008583  8984700.0
29950  0.000000  0.001305  0.0    0.0   0.0  0.001198  8985000.0
29951  0.000000  0.000652  0.0    0.0   0.0  0.000599  8985300.0
29952  0.010157  0.000000  0.0    0.0   0.0  0.000100  8985600.0
29953  0.000000  0.000978  0.0    0.0   0.0  0.000898  8985900.0

[29954 rows x 7 columns]

In [8]:
slots = validator_exits_category_set['slot']
columns = validator_exits_category_set.columns.drop('slot')
validator_exits_category_percentage = validator_exits_category_set[columns].divide(active_validators_category[columns]) * 100
validator_exits_category_percentage['slot'] = slots

validator_exits_category_percentage

,CEX,Liquid Restaking,Liquid Staking,Solo Stakers,Staking Pools,Unidentified,Unnamed: 7,total,slot
0,0.000000,NaN,0.000000,0.0,0.0,0.000000,NaN,0.000000,0.0
1,0.000000,NaN,0.000000,0.0,0.0,0.000000,NaN,0.000000,300.0
2,0.000000,NaN,0.000000,0.0,0.0,0.000000,NaN,0.000000,600.0
3,0.000000,NaN,0.000000,0.0,0.0,0.000000,NaN,0.000000,900.0
4,0.000000,NaN,0.000000,0.0,0.0,0.000000,NaN,0.000000,1200.0
...,...,...,...,...,...,...,...,...,...
29949,0.004618,0.0,0.001207,0.0,0.0,0.025814,NaN,0.009258,8984700.0
29950,0.000000,0.0,0.000905,0.0,0.0,0.000000,NaN,0.000335,8985000.0
29951,0.000000,0.0,0.001207,0.0,0.0,0.000759,NaN,0.000669,8985300.0
29952,0.000000,0.0,0.000000,0.0,0.0,0.000380,NaN,0.000112,8985600.0
29953,0.001680,0.0,0.001207,0.0,0.0,0.000380,NaN,0.001004,8985900.0

In [9]:
slots = validator_exits_pool_set['slot']
columns = validator_exits_pool_set.columns.drop('slot')
validator_exits_pool_percentage = validator_exits_pool_set[columns].divide(active_validators_pool[columns]) * 100
validator_exits_pool_percentage['slot'] = slots

validator_exits_pool_percentage

,Binance,Bitcoin Suisse,Coinbase,Ether.Fi,Kraken,Ledger Live,Lido,Mantle,OKX,Other Stakers,Rocketpool,total,slot
0,0.0,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.0
1,0.0,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.000000,0.000000,0.000000,300.0
2,0.0,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.000000,0.000000,0.000000,600.0
3,0.0,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.000000,0.000000,0.000000,900.0
4,0.0,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.000000,0.000000,0.000000,1200.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
29949,0.0,0.0,0.006505,0.0,0.0,0.0,0.0,0.013355,0.0,0.018430,0.008087,0.008583,8984700.0
29950,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.002273,0.012131,0.001198,8985000.0
29951,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.000505,0.016176,0.000599,8985300.0
29952,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.000252,0.000000,0.000100,8985600.0
29953,0.0,0.0,0.002891,0.0,0.0,0.0,0.0,0.000000,0.0,0.000252,0.016179,0.000898,8985900.0

In [10]:
validator_exits_size_percentage.to_csv('../int/validator_exits_size_percentage.csv')
validator_exits_category_percentage.to_csv('../int/validator_exits_category_percentage.csv')
validator_exits_pool_percentage.to_csv('../int/validator_exits_pool_percentage.csv')